name: Record Preview for PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  capture-preview:
    name: Capture Cloudflare Preview URL
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase client
        run: npm install @supabase/supabase-js

      - name: Record preview build in Supabase
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: node .github/scripts/record_pr_preview.cjs

