name: Supabase DB Push

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/migrations/**"

permissions:
  contents: read

concurrency:
  group: supabase-db-push
  cancel-in-progress: false

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure project is linked via config.toml
        run: |
          if [ ! -f supabase/config.toml ]; then
            echo "supabase/config.toml missing. Please run 'supabase link' locally once." && exit 1
          fi
          if ! grep -E '^project_id\s*=\s*"[a-z0-9]{20}"' supabase/config.toml > /dev/null; then
            echo "project_id missing/invalid in supabase/config.toml. Please run 'supabase link' locally." && exit 1
          fi

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

        # Requires repository secret SUPABASE_ACCESS_TOKEN
      - name: Push migrations to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push


